services:
    - docker
language: c
env:
  global:
  - ROCKER_VERSION=1.3.0
before_script:
  - curl -L https://github.com/grammarly/rocker/releases/download/${ROCKER_VERSION}/rocker_linux_amd64.tar.gz | sudo tar -C /usr/bin -xzf -
script:
  - ./build.sh
